### ISSUE TITLE
problem of the direct_fortran

### ISSUE THREAD

**Issue by lengjia** [kirthevasank/nasbot#2]
hi, I meet the problem when i follow the step 'bash make_direct.sh' & ' python simple_direct_test.py '
I have installed both python2 and python3 on my computer, after the 'bash make_direct.sh', 
 'ImportError: No module named direct' is occured when I use 'python2 simple_direct_test.py', 
 but it's work right "python3 simple_direct_test.py", what should I try to make it work on python2? Thanks!

**Comment by kirthevasank** [comment]
We haven't really encountered any issues with Python2. In fact, we have tested this more on Python2 than Python3. Can you include the output when you run it with Python2?

**Comment by lengjia** [comment]
`~/workplace/nasbot/utils/direct_fortran$ bash make_direct.sh 
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "direct" sources
f2py options: []
  skipping 'direct.pyf' f2py interface (up-to-date)
  adding 'tmp1/src.linux-x86_64-3.5/tmp1/src.linux-x86_64-3.5/fortranobject.c' to sources.
  adding 'tmp1/src.linux-x86_64-3.5/tmp1/src.linux-x86_64-3.5' to include_dirs.
  adding 'tmp1/src.linux-x86_64-3.5/direct-f2pywrappers.f' to sources.
build_src: building npy-pkg config files
running build_ext
new_compiler returns <class 'distutils.unixccompiler.UnixCCompiler'>
customize UnixCCompiler
customize UnixCCompiler using build_ext
********************************************************************************
<class 'distutils.unixccompiler.UnixCCompiler'>
archiver      = ['x86_64-linux-gnu-gcc-ar', 'rc']
compiler      = ['x86_64-linux-gnu-gcc', '-pthread', '-DNDEBUG', '-g', '-fwrapv', '-O2', '-Wall', '-Wstrict-prototypes', '-g', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
ranlib        = None
preprocessor  = ['x86_64-linux-gnu-gcc', '-pthread', '-E', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
linker_exe    = ['x86_64-linux-gnu-gcc', '-pthread']
compiler_cxx  = ['x86_64-linux-gnu-g++', '-pthread']
compiler_so   = ['x86_64-linux-gnu-gcc', '-pthread', '-DNDEBUG', '-g', '-fwrapv', '-O2', '-Wall', '-Wstrict-prototypes', '-g', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2', '-fPIC']
linker_so     = ['x86_64-linux-gnu-gcc', '-pthread', '-shared', '-Wl,-O1', '-Wl,-Bsymbolic-functions', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-g', '-fstack-protector-strong', '-Wformat', '-Werror=format-security', '-Wdate-time', '-D_FORTIFY_SOURCE=2']
libraries     = []
library_dirs  = []
include_dirs  = ['/usr/include/python3.5m']
********************************************************************************
customize Gnu95FCompiler
find_executable('gfortran')
Found executable /usr/bin/gfortran
exec_command(['/usr/bin/gfortran', '-dumpversion'],)
Retaining cwd: /home/chenweiwei/workplace/nasbot/utils/direct_fortran
_preserve_environment([])
_update_environment(...)
_update_environment(...)
exec_command(['/usr/bin/gfortran', '-Wall', '-g', '-ffixed-form', '-fno-second-underscore', '-fPIC', '-O3', '-funroll-loops', '-print-file-name=libgfortran.so'],)
Retaining cwd: /home/chenweiwei/workplace/nasbot/utils/direct_fortran
_preserve_environment([])
_update_environment(...)
_update_environment(...)
exec_command(['/usr/bin/gfortran', '-Wall', '-g', '-ffixed-form', '-fno-second-underscore', '-fPIC', '-O3', '-funroll-loops', '-print-file-name=libgfortran.so'],)
Retaining cwd: /home/chenweiwei/workplace/nasbot/utils/direct_fortran
_preserve_environment([])
_update_environment(...)
_update_environment(...)
exec_command(['/usr/bin/gfortran', '-Wall', '-g', '-ffixed-form', '-fno-second-underscore', '-fPIC', '-O3', '-funroll-loops', '-print-libgcc-file-name'],)
Retaining cwd: /home/chenweiwei/workplace/nasbot/utils/direct_fortran
_preserve_environment([])
_update_environment(...)
_update_environment(...)
customize Gnu95FCompiler using build_ext
********************************************************************************
<class 'numpy.distutils.fcompiler.gnu.Gnu95FCompiler'>
archiver        = ['/usr/bin/gfortran', '-cr']
compiler_fix    = ['/usr/bin/gfortran', '-Wall', '-g', '-ffixed-form', '-fno-second-underscore', '-Wall', '-g', '-fno-second-underscore', '-fPIC', '-O3', '-funroll-loops']
compiler_f77    = ['/usr/bin/gfortran', '-Wall', '-g', '-ffixed-form', '-fno-second-underscore', '-fPIC', '-O3', '-funroll-loops']
ranlib          = ['/usr/bin/gfortran']
linker_so       = ['/usr/bin/gfortran', '-Wall', '-g', '-Wall', '-g', '-shared']
linker_exe      = ['/usr/bin/gfortran', '-Wall', '-Wall']
version_cmd     = ['/usr/bin/gfortran', '-dumpversion']
compiler_f90    = ['/usr/bin/gfortran', '-Wall', '-g', '-fno-second-underscore', '-fPIC', '-O3', '-funroll-loops']
version         = LooseVersion ('5.4.0')
libraries       = ['gfortran']
library_dirs    = ['/usr/lib/gcc/x86_64-linux-gnu/5', '/usr/lib/gcc/x86_64-linux-gnu/5']
object_switch   = '-o '
compile_switch  = '-c'
include_dirs    = ['/usr/include/python3.5m']
`
after that, `direct.cpython-35m-x86_64-linux-gnu.so` is generated.
from the output, it uses the python3.5, but i don't know how to change it into python2

**Comment by lengjia** [comment]
I have fixed this problem, the f2py uses the python3, I uninstall the numpy of python, and it's fixed
