### ISSUE TITLE
Adding setup.py to make installable with pypi

### ISSUE THREAD

**Issue by dylancashman** [kirthevasank/nasbot#7]
Thanks for releasing all of your code for this.  Could you make a `setup.py` so that this is installable via pip?  It seems pretty close.  

FYI I'm looking to use the OTMANN distance in a separate project, but the local references are making it difficult for me to include just the distance without copying over all of the files and updating the paths.

**Comment by kirthevasank** [comment]
Hi Dylan,
We are actually developing a different library for BO which is pip installable: https://github.com/dragonfly/dragonfly/

OTMANN isn't there yet, but we aim to put it in there in a couple of weeks.

**Comment by dylancashman** [comment]
That's great.  Thank you.  I'm going to roll with this repo for the time being but I look forward to using dragonfly for OTMANN when it gets in there.

**Comment by kirthevasank** [comment]
In case you haven't noticed yet, OTMANN is now part of dragonfly.
